### ISSUE TITLE
MVPレビュー依頼

### ISSUE THREAD

**Issue by monakon** [monakon/Journalip#53]
お世話になります。MVPレビュー依頼を提出します。
以下の内容は、カリキュラム「卒業制作：MVPリリース」のissue用テンプレートを参考に作成しました。
ご確認よろしくお願いいたします。
***

## 各種情報
サービス名：Journalip（ジャーナリップ）
サービスURL：https://journalip.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

- [x] トップページ
- [x] 会員登録機能
- [x] ログイン機能
- [x] 記録投稿フォーム（文章）
- [x] 記録編集・削除機能
- [x] みんなの記録一覧
- [x] 自分の記録一覧
- [x] 記録詳細表示
- [x] ヘッダー（未ログインとログインで区別）

以下MVP以降の実装を予定しています
- [ ] 検索、結果一覧機能
- [ ] プロフィール表示
- [ ] プロフィール編集
- [ ] メールアドレス変更設定
- [ ] パスワード変更設定
- [ ] 旅の記録投稿フォーム（写真、画像）
- [ ] マイページ

###  思い出し機能（記録作成補助テンプレート）
- 投稿フォームでテンプレートの使用を選択できる（使わなくても投稿できる）予定でしたが、使わないと投稿できないように変更しました。

### ゲストログイン機能
- 会員登録なしで記事作成・閲覧を可能にする予定でしたが、MVPでは会員のみの機能としました。

### みんなの記事一覧
<img src="https://i.gyazo.com/6516a3969a83fdda6515d85f81d4d0de.png" width= "300px" >

### 記事投稿
<img src="https://i.gyazo.com/2a9f85fa5c9477a99fc09fe7c87893b3.png" width= "300px" >

### 記事詳細
<img src="https://i.gyazo.com/d46db865b94286d8701095d8760d0e08.png" width= "300px" >

### 未ログイン時ヘッダー
<img src="https://i.gyazo.com/23f73189683ba693691c3bb95e65460c.pngg" width= "300px" >

**Comment by ky0613** [comment]
LGTMです！
技術面でのアピール強化として、アプリ開発カリキュラムの「高度な機能」を検討してみましょう！
https://school.runteq.jp/v3/curriculums/application_development/chapters/6

**Comment by monakon** [comment]
お世話になります。
ご確認頂きありがとうございます！
LGTM嬉しいです！

本リリースに向けて、「高度な機能」を考えていきます！
