### ISSUE TITLE
本リリースレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [monakon/Journalip#90]
以下、レビュー内容になりますのでご確認ください。

### 技術
- `app/controllers/boards_controller.rb`のmypageメソッドでcurrent_userのboard情報を取得しているかとおもいますが、whereで取得するのではなく`current_user.boards`でも取得できるかと思うのでそちらも検討してください。
- carrierwaveやminimagickを使用するのであれば、投稿された画像の拡張子をwebpに変換する機能があっても良さそうかと思いました。（実装する場合は就活準備と並行して実装しましょう。）
- `app/controllers/users_controller.rb`のset_userで使っているfind_byだけ引数の書き方が他の記述のと違うので確認してみてください。（意図的にこのように記述してある場合は、こちらは気にしなくて大丈夫です。）

### ユーザビリティ
- マイページに遷移する時に、データのロードに時間がかかる印象なので、「ローディング画面」などを実装して、ユーザーに「データをロードしている」ことが伝わるようにしてあげると、体験が良くなるかと思います。
- 基本的にリンクの上にホバーすると、カーソルがpointerになる仕様かと思いますが、「押せるリンク（ボタン）」ということをユーザーにより視覚的に伝えるために、cssのhoverなどを使って、リンク自体にも動きをつけてあげると良さそうです。
- 投稿フォームにあるフォームの説明ですが、こちらはもと強調しても良さそうです。
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/6491fda97bc0ef7f0cc7242e1f9db5a6.png)](https://startup-technology.gyazo.com/6491fda97bc0ef7f0cc7242e1f9db5a6)

以上です！

上記レビューに関して、質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by monakon** [comment]
質問があってコメントしました！

「carrierwaveやminimagickを使用するのであれば、投稿された画像の拡張子をwebpに変換する機能があっても良さそうかと思いました。」

こちらの、技術のFBについて、``app/uploaders/board_image_uploader.rb``の``filename``メソッドで「すべてのアップロードファイルの拡張子をwebpに変更する」定義を書いているのですが、アドバイス頂いた機能に当てはまりますでしょうか？

アップロードした画像がwebpに変換されているか確認するために、アップロードした画像を名前を付けて保存してみると拡張子がwebpになっていることを確認しました。
これは開発・本番環境ともに動作しています。

[![Image from Gyazo](https://i.gyazo.com/ebe2896c3701d6277a638f98831c5639.png)](https://gyazo.com/ebe2896c3701d6277a638f98831c5639)

**Comment by tmtkzk0823** [comment]
> 「carrierwaveやminimagickを使用するのであれば、投稿された画像の拡張子をwebpに変換する機能があっても良さそうかと思いました。」
こちらの、技術のFBについて、app/uploaders/board_image_uploader.rbのfilenameメソッドで「すべてのアップロードファイルの拡張子をwebpに変更する」定義を書いているのですが、アドバイス頂いた機能に当てはまりますでしょうか？

こちら失礼しました！
上記でwebpに変換できているなら大丈夫そうです！
画像投稿系だと、大きさも大切になってくるかと思うので、サイズを統一する処理も追加されるといいと思います！

**Comment by monakon** [comment]
回答ありがとうございます！

>画像投稿系だと、大きさも大切になってくるかと思うので、サイズを統一する処理も追加されるといいと思います！
画像を表示する際に縦画像と横画像で同じように表示するということでしょうか？

**Comment by tmtkzk0823** [comment]
そうですね！
投稿系のアプリ件画像ありの場合、画像の大きさが統一されていると、アプリのとしてまとまりが出るので！

**Comment by monakon** [comment]
ありがとうございます！

**Comment by monakon** [comment]
レビュー内容をアプリに反映させました！

### 反映できたもの

- [x] ``app/controllers/boards_controller.rb``のmypageメソッドでcurrent_userのboard情報を取得しているかとおもいますが、whereで取得するのではなくcurrent_user.boardsでも取得できるかと思うのでそちらも検討してください

➔``@boards = current_user.boards``へ修正
[#91 投稿取得のコード修正](https://github.com/monakon/Journalip/pull/91/files)

- [x] carrierwaveやminimagickを使用するのであれば、投稿された画像の拡張子をwebpに変換する機能があっても良さそうかと思いました。（実装する場合は就活準備と並行して実装しましょう。）

➔上記で相談させていただいて解決しているので省略します

- [x] ``app/controllers/users_controller.rb``のset_userで使っているfind_byだけ引数の書き方が他の記述のと違うので確認してみてください。（意図的にこのように記述してある場合は、こちらは気にしなくて大丈夫です。）

➔set_userなしでも動作に問題ないので、当該コードは削除しました
[#91 退会処理コード修正](https://github.com/monakon/Journalip/pull/91/files)

- [x] 基本的にリンクの上にホバーすると、カーソルがpointerになる仕様かと思いますが、「押せるリンク（ボタン）」ということをユーザーにより視覚的に伝えるために、cssのhoverなどを使って、リンク自体にも動きをつけてあげると良さそうです。

➔「押せるリンク」と分かるように、ホバー時文字が太くなるようにスタイルを変更しました。
スマホでは分かりにくいので、ヘッダーメニューをアイコンにしてユーザがメニューだと分りやすいようにしました。
[#92 ユーザビリティ修正](https://github.com/monakon/Journalip/pull/92)
[#94 レイアウト調整](https://github.com/monakon/Journalip/pull/94)

### 未反映・検討しているもの

- [ ] マイページに遷移する時に、データのロードに時間がかかる印象なので、「ローディング画面」などを実装して、ユーザーに「データをロードしている」ことが伝わるようにしてあげると、体験が良くなるかと思います。

➔issuesにして検討します！

**Comment by tmtkzk0823** [comment]
確認しました！
大丈夫そうですね！
報告ありがとうございます！
